In [700]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
data=pd.read_csv(r'C:\Users\ATHUL AKSHAY\Desktop\Employee\Employee.csv')
data.head()

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore            3   34    Male          No   
1  Bachelors         2013       Pune            1   28  Female          No   
2  Bachelors         2014  New Delhi            3   38  Female          No   
3    Masters         2016  Bangalore            3   27    Male          No   
4    Masters         2017       Pune            3   24    Male         Yes   

   ExperienceInCurrentDomain  LeaveOrNot  
0                          0           0  
1                          3           1  
2                          2           0  
3                          5           1  
4                          2           1

In [701]:
data

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0     Bachelors         2017  Bangalore            3   34    Male          No   
1     Bachelors         2013       Pune            1   28  Female          No   
2     Bachelors         2014  New Delhi            3   38  Female          No   
3       Masters         2016  Bangalore            3   27    Male          No   
4       Masters         2017       Pune            3   24    Male         Yes   
...         ...          ...        ...          ...  ...     ...         ...   
4648  Bachelors         2013  Bangalore            3   26  Female          No   
4649    Masters         2013       Pune            2   37    Male          No   
4650    Masters         2018  New Delhi            3   27    Male          No   
4651  Bachelors         2012  Bangalore            3   30    Male         Yes   
4652  Bachelors         2015  Bangalore            3   33    Male         Yes   

      ExperienceInCurrentDomain  LeaveOrNot  
0                             0           0  
1                             3           1  
2                             2           0  
3                             5           1  
4                             2           1  
...                         ...         ...  
4648                          4           0  
4649                          2           1  
4650                          5           1  
4651                          2           0  
4652                          4           0  

[4653 rows x 9 columns]

In [657]:
data.shape

(4653, 9)

In [658]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4653 entries, 0 to 4652
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   Education                  4653 non-null   object
 1   JoiningYear                4653 non-null   int64 
 2   City                       4653 non-null   object
 3   PaymentTier                4653 non-null   int64 
 4   Age                        4653 non-null   int64 
 5   Gender                     4653 non-null   object
 6   EverBenched                4653 non-null   object
 7   ExperienceInCurrentDomain  4653 non-null   int64 
 8   LeaveOrNot                 4653 non-null   int64 
dtypes: int64(5), object(4)
memory usage: 327.3+ KB


In [659]:
for column in data.columns:
    print(data[column].value_counts)
    print("*"*20)

<bound method IndexOpsMixin.value_counts of 0       Bachelors
1       Bachelors
2       Bachelors
3         Masters
4         Masters
          ...    
4648    Bachelors
4649      Masters
4650      Masters
4651    Bachelors
4652    Bachelors
Name: Education, Length: 4653, dtype: object>
********************
<bound method IndexOpsMixin.value_counts of 0       2017
1       2013
2       2014
3       2016
4       2017
        ... 
4648    2013
4649    2013
4650    2018
4651    2012
4652    2015
Name: JoiningYear, Length: 4653, dtype: int64>
********************
<bound method IndexOpsMixin.value_counts of 0       Bangalore
1            Pune
2       New Delhi
3       Bangalore
4            Pune
          ...    
4648    Bangalore
4649         Pune
4650    New Delhi
4651    Bangalore
4652    Bangalore
Name: City, Length: 4653, dtype: object>
********************
<bound method IndexOpsMixin.value_counts of 0       3
1       1
2       3
3       3
4       3
       ..
4648    3
4649    2
4650    

In [660]:
data.isnull().sum()

Education                    0
JoiningYear                  0
City                         0
PaymentTier                  0
Age                          0
Gender                       0
EverBenched                  0
ExperienceInCurrentDomain    0
LeaveOrNot                   0
dtype: int64

In [661]:
data.dtypes

Education                    object
JoiningYear                   int64
City                         object
PaymentTier                   int64
Age                           int64
Gender                       object
EverBenched                  object
ExperienceInCurrentDomain     int64
LeaveOrNot                    int64
dtype: object

In [662]:
data['City'].value_counts()

Bangalore    2228
Pune         1268
New Delhi    1157
Name: City, dtype: int64

In [663]:
data['Education'].value_counts()

Bachelors    3601
Masters       873
PHD           179
Name: Education, dtype: int64

In [664]:
data['Gender'].value_counts()

Male      2778
Female    1875
Name: Gender, dtype: int64

In [665]:
data['JoiningYear'].value_counts()

2017    1108
2015     781
2014     699
2013     669
2016     525
2012     504
2018     367
Name: JoiningYear, dtype: int64

In [666]:
data['EverBenched'].value_counts()

No     4175
Yes     478
Name: EverBenched, dtype: int64

In [667]:
data['LeaveOrNot'].value_counts()

0    3053
1    1600
Name: LeaveOrNot, dtype: int64

In [668]:
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()
data['Education']=label_encoder.fit_transform(data['Education'])
data['City']=label_encoder.fit_transform(data['City'])
data['Gender']=label_encoder.fit_transform(data['Gender'])
data['EverBenched']=label_encoder.fit_transform(data['EverBenched'])

In [669]:
data['Education'].unique()

array([0, 1, 2])

In [670]:
data['City'].unique()

array([0, 2, 1])

In [671]:
data['Gender'].unique()

array([1, 0])

In [672]:
data['EverBenched'].unique()

array([0, 1])

In [673]:
data['JoiningYear'].value_counts()

2017    1108
2015     781
2014     699
2013     669
2016     525
2012     504
2018     367
Name: JoiningYear, dtype: int64

In [674]:
data['PaymentTier'].value_counts()

3    3492
2     918
1     243
Name: PaymentTier, dtype: int64

In [675]:
data['Age'].value_counts()

26    645
28    630
27    625
25    418
24    385
29    230
30    220
37    141
36    139
34    136
38    136
40    134
32    132
39    131
31    125
33    124
35    123
41     82
22     49
23     48
Name: Age, dtype: int64

In [676]:
data['ExperienceInCurrentDomain'].value_counts()

2    1087
4     931
5     919
3     786
1     558
0     355
7       9
6       8
Name: ExperienceInCurrentDomain, dtype: int64

In [677]:
data.dtypes

Education                    int32
JoiningYear                  int64
City                         int32
PaymentTier                  int64
Age                          int64
Gender                       int32
EverBenched                  int32
ExperienceInCurrentDomain    int64
LeaveOrNot                   int64
dtype: object

In [678]:
data.LeaveOrNot.describe()

count    4653.000000
mean        0.343864
std         0.475047
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         1.000000
Name: LeaveOrNot, dtype: float64

In [679]:
data.to_csv('employee cleaneddataset.csv')
data


Education  JoiningYear  City  PaymentTier  Age  Gender  EverBenched  \
0             0         2017     0            3   34       1            0   
1             0         2013     2            1   28       0            0   
2             0         2014     1            3   38       0            0   
3             1         2016     0            3   27       1            0   
4             1         2017     2            3   24       1            1   
...         ...          ...   ...          ...  ...     ...          ...   
4648          0         2013     0            3   26       0            0   
4649          1         2013     2            2   37       1            0   
4650          1         2018     1            3   27       1            0   
4651          0         2012     0            3   30       1            1   
4652          0         2015     0            3   33       1            1   

      ExperienceInCurrentDomain  LeaveOrNot  
0                             0           0  
1                             3           1  
2                             2           0  
3                             5           1  
4                             2           1  
...                         ...         ...  
4648                          4           0  
4649                          2           1  
4650                          5           1  
4651                          2           0  
4652                          4           0  

[4653 rows x 9 columns]

In [680]:
x=data.drop(['LeaveOrNot'],axis=1)
y=data['LeaveOrNot']

In [681]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import r2_score

In [682]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [683]:
x.shape

(4653, 8)

In [684]:
x_train.shape

(3722, 8)

In [685]:
x_test.shape

(931, 8)

In [686]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred_lr=lr.predict(x_test)
r2_score(y_test,y_pred_lr)

c:\Users\ATHUL AKSHAY\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


-0.34013711113872724

In [687]:
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
y_pred_dt=dt.predict(x_test)
dt

DecisionTreeClassifier()

In [688]:
dt.score(x_test,y_test)

0.8088077336197637

In [689]:
dt.score(x_train,y_train)

0.930951101558302

In [ ]:
rc=RandomForestClassifier()
rc.fit(x_train,y_train)
y_pred_rc=rc.predict(x_test)
y_pred_rc

In [698]:
rc.predict([[0,2013,2,1,28,0,0,3]])

c:\Users\ATHUL AKSHAY\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [691]:
rc.score(x_test,y_test)

0.8238453276047261

In [692]:
rc.score(x_train,y_train)

0.9306824288017195

In [702]:
import pickle
em=open('employee.pkl','wb')
pickle.dump(rc,em)

In [703]:
em1=open('employee.pkl','rb')
pk=pickle.load(em1)
pk

RandomForestClassifier()

In [708]:
prediction=pk.predict([[0,2013,0,3,26,0,0,4]])
prediction

c:\Users\ATHUL AKSHAY\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)